### ISSUE TITLE
Errore su diverso SegregationCode per stesso EC

### ISSUE THREAD

**Issue by giuseppearmanno** [pagopa/pagopa-print-payment-notice-service#62]
Ciao,
sto provando a stampare gli avvisi con il servizio. 
Sto testando su un EC in Esercizio che ha più stazioni (sincrone e asincrone): la stampa sulla prima stazione utilizzata continua a funzionare, ma se cambio la stazione ottengo il seguente errore

it.pagopa.print_payment_notice_service.client.ApiException: Message: Forbidden HTTP response code: 403 HTTP response body: {"title":"Not allowed for notice ci tax code","status":403,"detail":"The request has been executed for a creditor institution having a different tax code to the one onboarded, and without having allowance to manage notices for said ci"} HTTP response headers: {connection=[keep-alive], content-type=[application/json], date=[Wed, 04 Dec 2024 11:42:14 GMT], request-context=[appId=cid-v1:58b37248-3089-47ba-aa07-a2844fabe46a], strict-transport-security=[max-age=31536000; includeSubDomains], transfer-encoding=[chunked], vary=[Origin,Access-Control-Request-Method,Access-Control-Request-Headers], x-request-id=[1b78252913bcf0aa56008b08a8ea4f53]}

grazie mille

**Comment by jacopocarlini** [comment]
Ciao @giuseppearmanno 
L'errore ti dice che la `subkey` che stai usando non è abilitata ad operare sul `taxCode` dell'EC che hai inserito nel body di request.

Non capisco bene il discorso della stazione visto che in input il servizio prende il Codice Fiscale dell'ente e non l'id della stazione. 
Per poterti aiutare meglio potresti postare la curl (nascondendo i valori sensibili) che stai usando?

Grazie

**Comment by giuseppearmanno** [comment]
ciao @jacopocarlini ,

ho provato a chiamare la "generateNotice" con questi json

`noticeGenerationRequestItem: class NoticeGenerationRequestItem {     data: class NoticeRequestData {         creditorInstitution: class CreditorInstitution {             taxCode: 82500570013         }         debtor: class Debtor {             address: Corso Roma             buildingNumber: 1              city: Torino              fullName: ArmaXXX GiuseXXX             postalCode: 10100             province: TO             taxCode: RMXGPX86H25B945X         }         notice: class Notice {             code: 319000000000024881             discounted: null             dueDate: 60gg dalla data di notifica             installments: [class InstallmentData {                 amount: 200                 code: 319000000000025386                 dueDate: 60gg dalla data di notifica             }, class InstallmentData {                 amount: 200                 code: 319000000000025285                 dueDate: 60gg dalla data di notifica             }, class InstallmentData {                 amount: 200                 code: 319000000000025184                 dueDate: 60gg dalla data di notifica             }, class InstallmentData {                 amount: 200                 code: 319000000000025083                 dueDate: 60gg dalla data di notifica             }, class InstallmentData {                 amount: 200                 code: 319000000000024982                 dueDate: 60gg dalla data di notifica             }]             paymentAmount: 1000             reduced: null             subject: prova 12/12/24 1         }     }     templateId: TemplateInstalments }`


e poi con questo

`noticeGenerationRequestItem: class NoticeGenerationRequestItem {     data: class NoticeRequestData {         creditorInstitution: class CreditorInstitution {             taxCode: 82500570013         }         debtor: class Debtor {             address: Corso Roma             buildingNumber: 1              city: Torino              fullName: ArmaXXX GiuseXXX             postalCode: 10100             province: TO             taxCode: RMXGPX86H25B945X         }         notice: class Notice {             code: 302000000000023640             discounted: null             dueDate: 60gg dalla data di notifica             installments: [class InstallmentData {                 amount: 200                 code: 302000000000024145                 dueDate: 60gg dalla data di notifica             }, class InstallmentData {                 amount: 200                 code: 302000000000024044                 dueDate: 60gg dalla data di notifica             }, class InstallmentData {                 amount: 200                 code: 302000000000023943                 dueDate: 60gg dalla data di notifica             }, class InstallmentData {                 amount: 200                 code: 302000000000023842                 dueDate: 60gg dalla data di notifica             }, class InstallmentData {                 amount: 200                 code: 302000000000023741                 dueDate: 60gg dalla data di notifica             }]             paymentAmount: 1000             reduced: null             subject: prova 12/12/24 2 new dominio         }     }     templateId: TemplateInstalments }`


quindi modificando solo il segregation code e per quelli con segregation code 19 mi dà errore.

**Comment by jacopocarlini** [comment]
Ciao @giuseppearmanno 
sui nostri sistemi non risulta nessuna stazione associata con segregation code 19 per il taxCode 82500570013

**Comment by giuseppearmanno** [comment]
Ciao @jacopocarlini 
sul quel taxCode ho 2 stazioni attive una sincrona e una asicnrona che sto usando per i test.

Configurazione della stazione con Segregation code 19 su selfcare.uat
Codice stazione 08102710012_04
Tipo di connessione Asincrona
Comune di Sciolze 82500570013
Auxdigit 0/3
Segregation code 19


Configurazione della stazione con Segregation code 02 su selfcare.uat
Codice stazione 08102710012_03
Tipo di connessione Sincrona
Comune di Sciolze 82500570013
Auxdigit 0/3
Segregation code 02

devo registrare la stazione da qualche parte?
grazie
