### ISSUE TITLE
Errore Stampa Rate

### ISSUE THREAD

**Issue by giuseppearmanno** [pagopa/pagopa-print-payment-notice-service#63]
Ciao,
ho notato degli errori sulla stampa di alcune rate:
ad esempio se stampo una pratica con 13 rate o 16 rate ottengo una rata senza QR code e dati

<img width="848" alt="Screenshot 2024-12-04 at 13 06 24" src="https://github.com/user-attachments/assets/0a2d6f53-8687-450e-b920-557e0108dff1">
<img width="789" alt="Screenshot 2024-12-04 at 13 04 27" src="https://github.com/user-attachments/assets/e17094f0-27c0-49d3-8653-bfb2101d8c4d">

grazie mille

**Comment by jacopocarlini** [comment]
@giuseppearmanno 
Grazie della segnalazione. 
La prendiamo in carico appena possibile.

**Comment by giuseppearmanno** [comment]
Ciao,
sto usando TemplateInstalments per le rate.
